env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  import/no-unresolved: off
  no-param-reassign: off
  no-multi-assign: off
  no-unused-vars: warn
